### ISSUE TITLE
Do we plan to S3 (object store) ops with dt?

### ISSUE THREAD

**Issue by gurup3184** [RobinTMiller/dt#11]
Currently dt works well for NAS/SAN filesystem. Do we plan to support object storage, i.e. S3 as well?

**Comment by jhollowe** [comment]
One option would be to use https://github.com/s3fs-fuse/s3fs-fuse to mount a bucket to a path and then use can use DT like normal on that mount of the bucket.

You can also check out [Scripts/s3t.sh](https://github.com/RobinTMiller/dt/blob/master/Scripts/s3t.sh) which creates test files locally, uploads them, downloads them, and then verifies the contents.
