### ISSUE TITLE
How do I use it to test a Windows file system driver?

### ISSUE THREAD

**Issue by Zero3K** [RobinTMiller/dt#12]
*subject*

**Comment by Zero3K** [comment]
I figured it out, I used dt of=filepath limit=inf (where filepath is replaced with the path to the test file that is being generated and written to).

**Comment by RobinTMiller** [comment]
Generally, you'll wish to specify a file system data limit less that the free space available to avoid file system full conditions. The max data limit percentage option is useful. For example, maxdatap=75 will use up to 75% of the free file system space.  Please find predefined file system workloads below.

robin@LAPTOP-BJH5MV95 ~/GitHub/dt/windows/x64/Release
$ **./dt version**
    --> Date: August 18th, 2023, Version: 25.04, Author: Robin T. Miller <--

robin@LAPTOP-BJH5MV95 ~/GitHub/dt/windows/x64/Release
$ **./dt workloads file**
Valid Workloads:

    many_files: Populate directory with many files (requires ~1g space)
        min=b max=1m incr=4k limit=1m files=100 sdirs=3 depth=3 dispose=keep prefix='%d@%h' enable=lbdata disable=pstats

    incr_files: Create incrementing file sizes (requires ~1.36g space)
        files=256 min=b max=1m limit=64m prefix=%d@%h pattern=iot enable=fsincr dispose=keep

    file_percentages: Single file with read/write and random/sequential percentages
        bs=random limit=1g enable=btags flags=direct onerr=abort slices=10 readp=-1 randp=50 dispose=keep

    file_performance: Single file performance
        bs=32k limit=1g flags=direct slices=10 disable=pstats disable=compare dispose=keep

    vary_file_sizes: Create files with varying sizes (requires ~2.41g space)
        bs=random min_limit=b max_limit=5m incr_limit=vary files=100 sdirs=3 depth=3 maxdatap=75 dispose=keeponerror prefix='%d@%h' enable=lbdata,deleteperpass disable=pstats

    terabyte_file: Single terabyte file
        limit=15t slices=15 step=1g aios=4 bs=random pattern=iot prefix='%d@%h' enable=pstats dispose=keep

    sparse_files: Sparse files test
        bs=16k step=32k disable=pstats enable=lbdata dispose=keep

    web_file_server: Web File Server Workload
        bs=64k readp=95 randp=5 disable=verify flags=direct

    sio_many_files: Populate directory with many files concurrently (write only)
        iobehavior=sio bs=32k end=1g files=100 passes=1

    longevity_file_dedup: Longevity File System w/Dedup Workload
        workload=longevity_common min_limit=1m max_limit=2g incr_limit=vary dispose=keep flags=direct notime=close,fsync oflags=trunc maxdatap=75 threads=4 pf=x:\noarch\dtdata\pattern_dedup

    longevity_file_system: Longevity File System Workload
        workload=longevity_common workload=high_validation min_limit=1m max_limit=2g incr_limit=vary dispose=keep flags=direct notime=close,fsync oflags=trunc maxdatap=75 threads=4

    longevity_file_write_only: Longevity File System Write Only
        workload=longevity_file_system disable=raw,reread,verify

    san_file_system: SAN File System Workload
        bs=random limit=2g dispose=keeponerror iodir=vary iotype=vary keepalivet=5m workload=keepalive pattern=iot prefix='%d@%h' enable=btags onerr=abort disable=pstats notime=close,fsync oflags=trunc threads=4 enable=noprog noprogt=15s noprogtt=130s alarm=3s history=5 hdsize=128 enable=htiming enable=syslog runtime=12h stopon=C:\temp\stopit bufmodes=buffered,cachereads,cachewrites,unbuffered

    dt_dedup_pattern_file: Deduplication Pattern File (template)
        pf=x:\noarch\dtdata\pattern_dedup

    dt_file_system_dedup: File System Deduplication Workload 2x Data Factor
        workload=dt_dedup_common,dt_dedup_data_pattern dispose=keep flags=direct maxdatap=75 files=2 limit=2g maxdatap=75 threads=4 pattern=iot prefix='%U@%h'

    stopon_file: Stop dt File (template)
        enable=stopimmed stopon=C:\temp\stopit

    file_system_write_only: File System Write Only
        workload=san_file_system disable=raw,reread,verify


robin@LAPTOP-BJH5MV95 ~/GitHub/dt/windows/x64/Release
$

**Comment by Zero3K** [comment]
Okay. I found two issues with the driver thanks to it. It doesn't support sparse files and also seems to have a CPU usage issue when using enable=aio under Windows 7 x86. I have told the guy I have working on it about them and will have him fix those soon.
