### ISSUE TITLE
DT, with oflags=trunc does a setattr of size 0 making the fize size 0 and then writes data to it. Is there a way with dt wherein we could truncate an existing file (of size say 10MB) to a lesser size like 2M instead of 0?

### ISSUE THREAD

**Issue by RuchiDhanuka** [RobinTMiller/dt#13]

**Comment by RobinTMiller** [comment]
There are no dt options to truncate a file at a particular offset/size.Instead, assuming Linux is used, the truncate --size option can be used. dt provides a pass script where this truncation can be done between passes, or use truncate prior to starting dt. This has never been a test requirement up until now.Regards,Robin__________________________________________________________________________________"Wisdom is doing today what will benefit you in the future!" -Joyce MeyerOn Aug 13, 2024, at 11:19 PM, Ruchi Dhanuka ***@***.***> wrote:﻿

**Comment by RuchiDhanuka** [comment]
Thanks a lot. This worked like a charm
