### ISSUE TITLE
dt writes and appends for a runtime

### ISSUE THREAD

**Issue by RuchiDhanuka** [RobinTMiller/dt#14]
I am looking at using dt for append workload wherein I write a file say 'abc' of 1M, then append 1MB data to it and do this continuously together for a specified runtime. tried this using pass_cmd but it throws data miscompare when the append happens for the second pass. Any alternative ways to achieve this?

dt iobehavior=dt bs=64k dispose=keep enable=lockfiles of=./rsap limit=1m enable=debug,noprog,nate,retrydisc noprogt=60 noprogtt=120 disable=elmo_logging retry_error=5 retry_error=2 passes=2 pass_cmd="dt iobehavior=dt bs=64k dispose=keep of=./rsap limit=1m enable=debug,noprog,nate,retrydisc noprogt=60 noprogtt=120 disable=elmo_logging retry_error=5 retry_error=2 oflags=append;"

**Comment by RobinTMiller** [comment]
For specialized tests like this, it's best to create a dt script, like this one:

$ **cat rsap.dt**
iobehavior=dt bs=64k dispose=keep enable=lockfiles of=./rsap limit=1m enable=debug,noprog,retrydisc noprogt=60 noprogtt=120 retry_error=5 retry_error=2 oflags=trunc pattern=iot
iobehavior=dt bs=64k dispose=keep of=./rsap limit=1m offset=1m enable=debug,noprog,retrydisc noprogt=60 noprogtt=120 retry_error=5 retry_error=2 oflags=append pattern=iot
iobehavior=dt bs=64k dispose=keep if=./rsap enable=debug,noprog,retrydisc noprogt=60 noprogtt=120 retry_error=5 retry_error=2 pattern=iot
shell ls -ls rsap
$ **for pass in {1..2}**
> **do**
>     **./dt script=rsap**
> **done**

Please know, in the dt Github. there's a Scripts directory than can help guide you. Hope this helps!

**Comment by RuchiDhanuka** [comment]
Thank you very much. This indeed helps :)
