### ISSUE TITLE
Add dt.html link in README

### ISSUE THREAD

**Issue by netapp-nelc** [RobinTMiller/dt#5]
Hey Robin!!

I was forwarding this repo to some colleagues, and noticed that I couldn't find a link to the page http://scsifaq.sitemux.net/RMiller_Tools/dt.html from your README, and had to go looking in Google and my search history.  Could you add that link (or a more current one) in the README file?

I've found all the docs on that page to be extremely helpful.

--Chris N.

**Comment by RobinTMiller** [comment]
That's funny, a dated dt web page from nearly 20 years ago!

The guy who developed the SCSI FAQ sold this URL and its' contents a long
time ago. I was never involved with this.

A couple files exist in the html/ directory that could be updated. May
you'd like to update and contribute?

The dt user's guide is woefully out of date, and also needs updates!
Someone offered once, but did not follow through! 🙁

Once retired, I'll have time to update documentation, but actually I'm
thinking about a blog, just not sure where yet.

Regards,
Robin

**Comment by netapp-nelc** [comment]
Robin

That's hilarious... I always assumed that page was an antique that you put together.

In any case I should be able to put a lot of cycles towards dt in the coming 2 months.  I'll look into updating some of the doc :)

--Chris N.
